exclude: >
    (?x)(
        ^.*\b(migrations)\b.*$
    )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length=79]

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=79
          - --ignore=E203,VNE001,W503,CFQ002
          - --docstring-convention=numpy
          - --max-function-length=36
        additional_dependencies:
          - flake8-assert-msg==1.1.1
          - flake8-comprehensions==3.11.1
          - flake8-docstrings==1.7.0
          - flake8-functions==0.0.7
          - pep8-naming
