name: deltri
channels:
  - conda-forge
  - defaults
dependencies:
  - black==22.6.0
  - matplotlib==3.6.2
  - mpi4py
  - numpy==1.23.5
  - pip==22.3.1
  - scipy==1.10.0
  - pip:
    - pre-commit==3.0.4
    - requests==2.28.2
